IBM/rotisserie

Dockerfile
app.js

* The 8.1.2-wheezy nodejs docker image does not behave correctly. For
now I've switched it to just run on ubuntu. This increases image
build time since nodejs needs to be installed (there is no official
nodejs ubuntu docker image that I can see).
* Dockerfile now requires a build argument, which is the twitch oauth
token used by the app.
* Timing tweaks to ensure all streams get processed in a docker
container.

Dockerfile fixes and timing tweaks

---

package-lock.json
package.json

Handlebars was used in the now-removed writeIndex() function, and is
no longer required.

Remove handlebars from dependencies

---

public/index.html

Since we're serving jquery oursleves, we don't need the integrity and
crossorigin fields.

Remove integrity and crossorigin malarkey

---

app.js

We shouldn't crash the app if the array of streams is empty, just stay
on the same stream until the next iteration.

Don't crash if array.length == 0

---

app.js

While paging through the whole list would eventually be better, just
grabbing 100 to start with is four times better than what we are doing
today.

Query for 100 streams instead of 25

---

.eslintignore
README.md
app.js

* TravisCI badge was still pointed at the old repo. This will update it.
* Updates eslint docs for the inclusion of promises so TravisCI will
resume passing.
*  Add bootstrap, jquery, and popper js files to .eslintignore.

Update travisCI badge and eslint docs for promises

---

ocr.js

Currently this function only logs the file which tesseract
failed to parse. This change logs the error message from
tesseract as well to aid in debugging.

Add additional logging to /process_pubg

---

README.md

Walked through setup again and ran into a few issues with the changes that have been made since the last README update. Added in the OCR_HOST changes. Moved environment variables from the build line to the run line so that we can build images without tokens.

Updated README sections for Local and Docker

---

deploy/images/app.Dockerfile
deploy/images/ocr.Dockerfile

The previous Alpine images failed due to missing English training
data. The Alpine package for tesseract 3.04 does not install that
training data so it must be downloaded manually.

Alpine images redux

---

.travis.yml
tests/build-containers
tests/deploy-containers
tests/test_ocr_service.sh

* The CI run has been split into two stages: linting and testing
the OCR application. If linting fails the CI run will abort.
* The container build process is now tested.
* The test_ocr_service script has been changed to use the newly
built container instead of starting the OCR process itself.

Update testing process

---

.eslintrc.js
app.js

An instance of the built-in Error object is now passed to the
rejection and a corresponding eslint rule to enforce that has
been enabled. A non-existent variable in the error message has
also been fixed.

Handle unhandled promise rejection

---

README.md
app.js
deploy/rotisserie.yaml

Prior to this, the main app was told by environment variable where the
OCR service was located. The location was the main website and the
/process_pubg endpoint. This meant we had to pipe /process_pubg through
to the ocr service in the ingress controller, which also introduced some
SSL issues.
Now, the main app looks at injected kubernetes environment variables to
discover where the ocr service is running, and hits it directly over
http.
This has probably broken the 'run containers locally' instructions,
which hopefully someone can noodle about. We don't want to inject
environment vars at build time that are later needed by k8s... even if
they might get overwritten.

Use k8s service discovery for ocr service

---

README.md
package-lock.json

Moved creation of environment variables into a new section since it is
shared by local and docker. Removed "npm install ." from the image
build section since it is only needed for running the app locally.
Removed the link section when running the containers since it is
depreciated, instead we will specify the IP + Port.

Updated local and docker deploy documentation

---

README.md
deploy/rotisserie.yaml
rotisserie-app.yaml
twitch-auth-secrets.yaml

Changed token-secrets to twitch-auth-secrets so that we can add clientID to the same secret. Changed references for rotisserie secrets to twitch-auth so that the production application matches one off kubernetes deployments.

Added clientID to secrets to support new api

---

README.md

The license was changed from MIT to Apache 2.0, but the documentation
was not updated.

Update license blurb/badge in README

---

app.js

The box containing the number of players alive has shifted slightly
with the test server (and 1.0 pubg release on the 12/20/2017). This
will correct the cropScreenshots function to center over this new
location.
We might not want to merge yet, but most people streaming PUBG will
be streaming the test server until the 1.0 release, and this will
need to be fixed anyway.

Adjust crop area for test server and 1.0

---

Makefile
README.md
deploy/images/make-image.sh
deploy/rotisserie.yaml
docs/architecture/kubernetes.md
rotisserie-app.yaml
rotisserie-secrets.yaml

Added a few options to the Makefile + added some information about how to use it. Removed sudo from the makefile and make-images file since we should assume regular users can use docker. Changed twitch-auth-secrets to rotisserie-secrets so that it will be more generic. We can use this file for future secrets that may not be related to twitch.

Added options to Makefile and changed secrets file

---

deploy/kube-lego.yaml
docs/architecture/kubernetes.md

Replaced default-http-backend with rotisserie-static in the kube-lego.yaml. We can use the static container as the default backend to provide 404s. Removed default-http-backend deployment and service setup in kube-lego.yaml. Updated documentation to reflect new values in yaml examples.

Removed default-http-backend and added static

---

README.md
package.json

I went ahead and published rotisserie to npm. However, the name
rotisserie was taken on npmjs, is deprecated, but seems to still be
kept around for unknown reasons. This will update the name of the
package in package.json as well as the npm badge in the readme, as it
previously pointed to the old pubgredzone package which is super old.

Update package.json to reflect new npm package

---

deploy/kube-lego.yaml

Added RBAC ClusterRoleBinding so that Kube-Lego resources have enough permissions to read ingress resources.

Added RBAC for Kube-Lego

---

Makefile
deploy/rotisserie.yaml

Since we have multiple people deploying the application it looks sloppy using docker repositories. Switched back to using the container registry. Tested with a deployment on my test domain and didn't run into any issues.

Revert back to bluemix container registry

---

helm/rotisserie/.helmignore
helm/rotisserie/Chart.yaml
helm/rotisserie/templates/_helpers.tpl
helm/rotisserie/templates/kube-lego.yaml
helm/rotisserie/templates/letsencrypt.yaml
helm/rotisserie/templates/rotisserie-secrets.yaml
helm/rotisserie/templates/rotisserie.yaml
helm/rotisserie/values.yaml

Setup helm for deploying rotisserie. Added options for multiple hostnames in ingress resources. Configured in a way to allow for multiple deployments in the same namespace without overlap. Tested against a dev kubernetes cluster to verify that it works.

Added Helm as an option for deploying the app

---

helm/rotisserie/Chart.yaml
helm/rotisserie/templates/kube-lego.yaml

The old configmap names were still setup in the templates. This worked on test clusters since they were never removed. After removing them in prod I ran into issues finding the configmap resources using the old naming style, but was able to resolve it by using the new name. Also moved the release to 0.1.1 and added sources in the Chart file.

Updated configmaps in templates to match naming

---

README.md

The npm badge is no longer needed, as rotisserie is in no way
being shipped as an npm package anymore and that package is
way out of date.
The docker build badge is no longer needed as we have migrated
over to the IBM Cloud Container Registry.
Signed-off-by: Cullen Taylor <mctaylor@us.ibm.com>

Remove unneeded badges from README.md

---

app.js
package-lock.json
package.json

This will make the log messages a little more production ready. It
uses the log package from npm, and just adds a time stamp and log
level (INFO or ERROR) to each log message. It still prints to the
console so kubectl logs will work just fine.
Signed-off-by: Cullen Taylor <mctaylor@us.ibm.com>

Add timestamps and log levels to log messages

---

helm/rotisserie/templates/rotisserie-issuer.yaml
helm/rotisserie/templates/rotisserie.yaml
helm/rotisserie/values.yaml

Switched from a clusterissuer to an issuer. This will create a per install issuer which will be named and controlled by the helm release name. Also added the option for setting the namespace for Cert-Manager in the values file.

Changed from clusterissuer to issuer

---

package-lock.json
package.json

hoek v4.2.0 has a security flaw which makes it vulnerable to prototype
pollution, and GitHub keeps yelling about it. This modifies
package.json and package-lock.json to upgrade the version of hoek
that is installed when running `npm install`.
Signed-off-by: Cullen Taylor <mctaylor@us.ibm.com>

Upgrade hoek version to fix vulnerability

---

deploy/images/ocr.Dockerfile
ocr/ocr.py
tests/test_ocr_service.sh

A new endpoint has been added to the OCR service which
uses a model trained for Fortnite to identify remaining
players.

Add support for Fortnite to OCR service
